### ISSUE TITLE
UNT0010 Should apply to all Components, not just MonoBehaviours

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#108]
#### Bug description

[UNT0010](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0010.md)

Calling `new MyBehaviourScript` where `MyBehaviourScript : MonoBehaviour` triggers the warning.

But calling `new CharacterController` or `new BoxCollider` does not.

#### Expected behavior

The warning should apply to everything inheriting from `Component`, not just `MonoBehaviour`.

**Comment by sailro** [comment]
Indeed this rule should be extended to all components
