### ISSUE TITLE
VSCode Omnisharp - Multiple failures to suppress

### ISSUE THREAD

**Issue by Gryhyphen** [microsoft/Microsoft.Unity.Analyzers#111]
#### Bug description
- Version of analyzers assembly: 1.8.2
- Analyzer rule: USP0006, USP0004, USP0003, probably others
- Error (exception message, type, and callstack where applicable): Fails to suppress rules

#### To Reproduce
Steps or code to reproduce the behavior:
1. Install vscode, unity and the right .net sdk
2. Install C# extension, Debugger for Unity and NuGet Packet Manager
3. Create a unity project, select vscode as editor and generate a project for code hinting setup stuff.
4. For some inexplicable reason, make sure you have visual studio installed (with the unity workload) and make sure the project/solution is aware of it. You do not need to be logged in to VS.
5. Enable royslin analyzers following this guide:  https://www.strathweb.com/2019/04/roslyn-analyzers-in-code-fixes-in-omnisharp-and-vs-code/
6. Using NuGet Packet manager, download/install Microsoft.Unity.Analyzers > 1.8.2
7. Run `dotnet restore <solution_name>` (Command should come with .net sdk)
8. Restart omnisharp.
9. Create some example scripts/monobehaviours.

#### Expected behavior
I expect the rules to be suppressed. Other rules such as UNT0008 do show up.

#### Screenshots
IDE0051 - Not suppressed by USP0006 (Although, I don't actually understand this rule because I don't understand why an unused private variable is useful)
IDE0044 - Not suppressed by USP0004
![image](https://user-images.githubusercontent.com/7694072/94329782-5f5f9900-0001-11eb-9759-21ba8e77165b.png)
IDE0051 - Not suppressed by USP0003
![image](https://user-images.githubusercontent.com/7694072/94329904-6044fa80-0002-11eb-9db7-900384dd467f.png)
Success of UNT0008
![image](https://user-images.githubusercontent.com/7694072/94330794-0268e080-000b-11eb-8a40-b8909bc1d1b9.png)

#### Additional context
I'm working on setting up code guidelines and linting for my team. I'm focusing on roslyn/omnisharp support for VS and VS Code, but I think that roslyn/omnisharp can be used by other editors and just roslyn CI? (Although not 100% sure what CI is as I've never had a chance to work on a project with it - but someone on my team might be interested in it).

From what I understand, anything outside of Visual Studio technically isn't supported by this project, but I'd still like to get this working if possible.

Not sure what is going on with needing VS installed, and not sure if the unity workload is needed or just a C# workload, but either way I think it's odd that the thing won't work in VS Code unless VS is installed and the project files know about it.

Got the idea to try installing the analyzer based on: https://community.sonarsource.com/t/add-c-support-for-vscode-sonarlint/5888

Thought that if sonarlint could do it, no reason why other analyzers on NuGet couldn't either.

**Comment by sailro** [comment]
Hello @Gryhyphen, yes we are aware of this, but the bug is not on our side but rather on the omnisharp side.

We are tracking this original issue here:
https://github.com/OmniSharp/omnisharp-roslyn/issues/1711

So currently, analyzers are working (UNT*), but suppressors (USP*) are not.

Thanks!
