### ISSUE TITLE
Add a SonarQube plugin for the analyzer

### ISSUE THREAD

**Issue by tallior** [microsoft/Microsoft.Unity.Analyzers#112]
#### Problem statement
I'd like to have better integration of these analyzers in SonarQube

#### Proposed solution
SonarQube offers an SDK to automatically create a "wrapper" plugin around Roslyn analyzers so they can be better integrated, read here:
https://devblogs.microsoft.com/devops/sonarqube-scanner-for-msbuild-v2-0-released-support-for-third-party-roslyn-analyzers/

It could be nicer to have such a plugin for the Unity analyzers.

**Comment by sailro** [comment]
Hello,

SonarQube is outside the scope of this project, and we have no plan so far for supporting this.

Given we are now able to produce a nuget package for our analyzers, it should be quite easy to consume thought using `https://github.com/SonarSource/sonarqube-roslyn-sdk`.

The SDK uses information from the NuGet package to populate the fields in the generated plugin that affect how the plugin is described in the Update Centre in the SonarQube UI
