### ISSUE TITLE
IDE0090: 'new' expression can be simplified

### ISSUE THREAD

**Issue by aybe** [microsoft/Microsoft.Unity.Analyzers#115]
#### Bug description

So, after updating to versions below, this appears like in the screenshot below.

#### Expected behavior

It should be suppressed because Unity does not yet support C# 9.

And you might have guessed it, applying the fix results in an error.

#### Screenshots

![devenv_2020-11-11_20-26-48](https://user-images.githubusercontent.com/1537591/98855425-42b9dc00-245c-11eb-9880-a732e4711d9b.png)

#### Additional context

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 1.0

Unity 2021.1.0a4.949

VSTU 4.8.2.0

**Comment by sailro** [comment]
In this case I think it is more up to the project generation system to set the language level to the proper version instead of latest.
We are already doing this for Unity 2020.1 and < which does not support C#8

**Comment by aybe** [comment]
That's exactly the problem, there is `latest`. I'll report at Unity then, thanks !

**Comment by sailro** [comment]
Nope that's up to us :) we maintain the VS Editor package

**Comment by aybe** [comment]
Oh, okay then! 😂

**Comment by sailro** [comment]
Fixed, will be released with the VS Editor package v2.0.6

**Comment by aybe** [comment]
Nice, thanks !
