### ISSUE TITLE
UNT0006 raised when method signature is correct

### ISSUE THREAD

**Issue by aybe** [microsoft/Microsoft.Unity.Analyzers#118]
#### Bug description

It says that signature is incorrect but it isn't.

https://docs.unity3d.com/ScriptReference/AssetPostprocessor.OnAssignMaterialModel.html

Visual Studio Editor Version 2.0.5 - November 04, 2020

#### Screenshots

![devenv_2020-11-17_16-58-28](https://user-images.githubusercontent.com/1537591/99413624-4505b580-28f6-11eb-9f2e-f2bf56c218d8.png)

**Comment by sailro** [comment]
I repro. In fact it's working as expected for simple types (like primitives), but we have an issue with Unity types:

![image](https://user-images.githubusercontent.com/638167/99597149-64f7b080-29ac-11eb-930b-fe66032b8f29.png)

**Comment by sailro** [comment]
Good catch, the return type was `void` in our stub reference instead of `Material`. I re-checked all messages from `AssetPostprocessor` we should be good now.

Thanks

**Comment by aybe** [comment]
Nice, thanks!
