### ISSUE TITLE
How to use these with VSCode?

### ISSUE THREAD

**Issue by marcospgp** [microsoft/Microsoft.Unity.Analyzers#122]
Is there a simple way to enable these in VSCode?

**Comment by sailro** [comment]
See https://github.com/OmniSharp/omnisharp-roslyn/issues/1711

You can use our diagnostics, but you cannot use our suppressors so far.

**Comment by marcospgp** [comment]
@sailro I had checked out that thread actually (you can see the latest comment is from me). I couldn't find the information there on how to get the Unity analyzers to be run on VSCode.

Do I have to build the .dlls from this repository? Can I download them using NuGet? Do I have to install Visual Studio? How did you do it?

**Comment by sailro** [comment]
No you don't need to install Visual Studio.

We have a nuget here:
https://www.nuget.org/packages/Microsoft.Unity.Analyzers

Check this page:
https://www.strathweb.com/2019/04/roslyn-analyzers-in-code-fixes-in-omnisharp-and-vs-code/

**Comment by marcospgp** [comment]
@sailro I used [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=jmrog.vscode-nuget-package-manager) to install the `Microsoft.Unity.Analyzers` package, and added an `omnisharp.json` file to the project after enabling the setting mentioned in the page you linked.

I still am not able to see the Unity analyzers in action, however:

![image](https://user-images.githubusercontent.com/3464445/101983052-030b2d80-3c70-11eb-8f87-f00bfcb1b014.png)

The code above should trigger `UNT0001 Empty Unity message`.

This is what my `omnisharp.json` looks like:

```
{
    "RoslynExtensionsOptions": {
        "EnableAnalyzersSupport": true
    }
}
```

Do I need to add a direct link to the package there? If so, how do I figure out where the nuget extension is installing packages to?

Thanks!

**Comment by marcospgp** [comment]
Oh wow! I went on a journey but I finally did it!

Ok so trying to install packages using any NuGet installer extension is pointless because it seems Unity won't allow anything to mess with its `.csproj` files. One extension failed silently, while another threw an obscure error, but all points to that.

So then I tried downloading the package manually from [the NuGet website](https://www.nuget.org/packages/Microsoft.Unity.Analyzers/), then extracting `Microsoft.Unity.Analyzers.dll` from the package (using 7zip) onto my project's assets folder, and finally referencing it in the `omnisharp.json` file at the root of the project:

```
{
    "RoslynExtensionsOptions": {
        "EnableAnalyzersSupport": true,
        "LocationPaths": [
            "./Assets/NuGet/microsoft.unity.analyzers.1.9.0/analyzers/dotnet/cs"
        ]
    }
}
```

And now it works:

![image](https://user-images.githubusercontent.com/3464445/101983593-fab4f180-3c73-11eb-809c-ed1be51e53ab.png)

This was definitely not obvious and way harder than it needed to be. Shame that there's no clear step by step tutorial on how to do this anywhere 😢

**Comment by 1hko** [comment]
@marcospgp there are clear instructions on this page: https://code.visualstudio.com/docs/other/unity#_enabling-unity-warnings

The page also recommends you do not put `NuGet` in your `Assets` folder. You should probably move it to your projects root instead.

**Comment by marcospgp** [comment]
Thanks @1hko , though it was I who wrote that section of the guide ahaha

**Comment by danvim** [comment]
https://github.com/vad710/UnityEngineAnalyzer#jetbrains-rider-integration specifies an alternative way that also works with Rider.

**Comment by Energiz3r** [comment]
@danvim, did you intend to reference different versions of the analyzers (1.9.0 vs 1.12.0)?

**Comment by danvim** [comment]
> @danvim, did you intend to reference different versions of the analyzers (1.9.0 vs 1.12.0)?

That was unintentional. I was directly copying code from my project. Thanks for reminding. 😅

**Comment by Slime-Bob** [comment]
> So then I tried downloading the package manually from [the NuGet website](https://www.nuget.org/packages/Microsoft.Unity.Analyzers/), then extracting `Microsoft.Unity.Analyzers.dll` from the package (using 7zip) onto my project's assets folder, and finally referencing it in the `omnisharp.json` file at the root of the project:

Does this mean you need to make a copy and extract the analysers everytime you create a new unity project?

**Comment by WeirdBeardDev** [comment]
Yup, that's what that means.

**Comment by boyestrous** [comment]
@marcospgp Thanks for these instructions (and the updates to the vscode docs). They are still helpful 2 years later!

**Comment by Chizaruu** [comment]
> > So then I tried downloading the package manually from [the NuGet website](https://www.nuget.org/packages/Microsoft.Unity.Analyzers/), then extracting `Microsoft.Unity.Analyzers.dll` from the package (using 7zip) onto my project's assets folder, and finally referencing it in the `omnisharp.json` file at the root of the project:
> 
> Does this mean you need to make a copy and extract the analysers everytime you create a new unity project?

Not anymore. I forked the project and ensured that omnisharp.json and the nuget dll were automatically generated.
https://github.com/Chizaruu/com.tsk.ide.vscode

**Comment by Darender** [comment]
> Oh wow! I went on a journey but I finally did it!

Crazy genius, you have no idea how much I had to search the internet to find your solution, thank you!

**Comment by sailro** [comment]
We updated [VSCode documentation](https://code.visualstudio.com/docs/other/unity#_enabling-unity-warnings) after the release of the new Unity extension for VSCode

**Comment by marcospgp** [comment]
> We updated [VSCode documentation](https://code.visualstudio.com/docs/other/unity#_enabling-unity-warnings) after the release of the new Unity extension for VSCode

So now there are no instructions on how to add third party analyzers to a Unity project so that the warnings will be displayed in VSCode?
