### ISSUE TITLE
UNT0014 doesn't let you GetComponent for a custom MonoBehaviour

### ISSUE THREAD

**Issue by marcospgp** [microsoft/Microsoft.Unity.Analyzers#126]
I don't understand [UNT0014](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0014.md). If I create a custom `Enemy` script and assign it to a gameobject, why can't I retrieve it from another script using `GetComponent`?

**Comment by WeirdBeardDev** [comment]
In your example, the `Enemy` script would be a Unity Component, so it would not raise [UNT0014](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0014.md).  [UNT0014](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0014.md) only applies to non-Unity Components.  In the screenshot below I created a `int i = GetComponent<int>();` which raises [UNT0014](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0014.md), and underneath it I created a `var x = GetComponent<Zone>();` where the `Zone` class derives `MonoBehaviour` and it does not raise [UNT0014](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0014.md).

![Screenshot 2021-01-06 103507](https://user-images.githubusercontent.com/26331356/103786853-eb268f80-500a-11eb-9c44-e4cf7ce4951e.png)

I hope this helps clarify matters.

**Comment by marcospgp** [comment]
Thank you, that does clear it up! I was probably getting the error because
some other file in my project had an error and thus the project wasn't
being compiled & updated.

Maybe this info could be added to the docs though?

**Comment by sailro** [comment]
Thanks @WeirdBeardDev and @marcospgp 

Yes `GetComponent`, `GetComponents`, `GetComponentInChildren`, `GetComponentsInChildren`, `GetComponentInParent`, and `GetComponentsInParent` should be called only with Types that extend `UnityEngine.Component`, or Types that are an Interface.

This is not specific to the Unity context but yes, compilation errors can alter the code model analysis made by diagnostics (like in this case detecting that a type properly extends  `UnityEngine.Component`). 

Closing.
