### ISSUE TITLE
Warn about improper usage of SerializeField

### ISSUE THREAD

**Issue by jbevain** [microsoft/Microsoft.Unity.Analyzers#14]
#### Problem statement
Because the `SerializeField` attribute does not have an `AttributeUsage` attribute limiting its usage to fields, people sometimes mistakenly use the `SerializeField` on properties. We should have an analyzer warning about it.

Also, we've seen people using `SerializeField` on a public field, which is not necessary either.

#### Proposed solution
In both cases, we can safely offer to remove the attribute.

**Comment by SilentSin** [comment]
It would also be worth having a warning when `[SerializeField]` is used on a field that doesn't follow the [Seriallization Rules](https://docs.unity3d.com/Manual/script-Serialization.html): not `static`, `const`, or `readonly`, and is a type that Unity can actually serialize.

**Comment by jbevain** [comment]
@SilentSin thanks for pointing that out, we should definitely handle those rules.
