### ISSUE TITLE
UNT0008 : docs here say an auto-fix will be available, but there isn't one.

### ISSUE THREAD

**Issue by elenzil** [microsoft/Microsoft.Unity.Analyzers#154]
#### Bug description
In VS2019, with UNT0008, the only options for alleviation are Suppression.
However the docs in this repo suggest that a proper fix should also be available.
Perhaps I'm arriving at UNT0008 through some other mechanism than the MS Unity Analyzer tho.
Link to the doc:
https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0008.md

- Version of analyzers assembly:    How does one find this ?
- Analyzer rule:  UNT0008

#### To Reproduce
Steps or code to reproduce the behavior:
1. write something like "FindObjectOfType<Camera>()?.gameObject.SetActive(false)".
2. get UNT0008, good.
3. potential fixes only include suppression, bad.

#### Expected behavior
The potential fixes should include a refactor to check against null with !=.

**Comment by sailro** [comment]
Indeed this quick fix was added quite recently. It should be published with `Visual Studio 2019 16.10`.

But in your case the codefix will not be enabled because a method invocation could have side effects.

It will work with the following test case though:

```csharp
var foo = FindObjectOfType<...>();
var bar = foo?.gameObject;

=>

var foo = FindObjectOfType<...>()
var bar = foo == null ? foo.gameObject : null;


```
