### ISSUE TITLE
Missing analysers UNT0019 through to UNT0023

### ISSUE THREAD

**Issue by mattdufeu** [microsoft/Microsoft.Unity.Analyzers#156]
I've got a Unity 2019.4.20f1 project, running on the latest version of Visual Studio Community, 16.9.2, but I'm missing analysers UNT0019 through to UNT0023, i.e. all the new ones in released in 1.10.0.

If I download the NuGet file, extract the dll and reference that from within Visual Studio it works. In that I get the newer analysers and my .csproj file is updated so the ItemGroup is referencing the new dll instead of "C:\Program Files (x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll".

Unfortunately when Unity is restarted and I open Visual Studio again it seems to re-write this ItemGroup so it points back to "Program Files".

Is there a way to stop that happening? Should I have 0019 to 0023 or do I need to be on a newer version of Unity?

**Comment by sailro** [comment]
Hello,

So 1.10.0 will be released along with Visual Studio Tools for Unity 4.10, included in Visual Studio 16.10.

Until then there is a way to consume a custom version:

You can add the following script in an `Editor` folder of your Unity project to alter project generation:

```csharp
using UnityEditor;
using System.Text.RegularExpressions;

public class UseMyCustomAnalyzersPostProcessor : AssetPostprocessor
{
	public static string OnGeneratedCSProject(string path, string content)
	{
		return string.Replace(@"C:\Program Files (x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll", @"custom\path\to\your\Microsoft.Unity.Analyzers.dll")
	}
}
```
