### ISSUE TITLE
Efficient use of Vector math

### ISSUE THREAD

**Issue by paulio** [microsoft/Microsoft.Unity.Analyzers#157]
#### Problem statement
It's very easy to write something like myVector  * speed * boost but it creates unnecessary vector math. i.e. VectorMult * VectorMult. It's more efficient to rewrite it as; speed * boost * myVector -> floatMult * VectorMult

#### Proposed solution
Analyzer that detects the order of operations on a vector and suggests a change in order.

**Comment by sailro** [comment]
Hi @paulio

Do you have a benchmark to share to show effective benefits? (Operator precedence/optimization can be tricky sometimes -especially when using operator overrides like in this case with Vectors-). 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/

**Comment by paulio** [comment]
To be clear it's not actually operator precedence, it's the order of the variables. Non vector scalers first, then vectors. See 'Vector and quaternion math and order of operations' https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity7.html

**Comment by sailro** [comment]
![image](https://user-images.githubusercontent.com/638167/116495177-46e58480-a857-11eb-88df-9a188a865498.png)
