### ISSUE TITLE
USP0016 only suppresses warning on fields/properties inheriting from UnityEngine.Object

### ISSUE THREAD

**Issue by guyguy2001** [microsoft/Microsoft.Unity.Analyzers#197]
#### Bug description

- Version of analyzers assembly: I'm not sure how to check this, but I found the code responsible for this in master (d0f2344)
- Analyzer rule: USP0016
- Error (exception message, type, and callstack where applicable): I receive the following error when I shouldn't: "CS8618 - Non-nullable field is uninitialized. Consider declaring the field as nullable."

#### To Reproduce
Add the following code to your Unity project (in the file Assets/Scripts/Test.cs):
```csharp
#nullable enable
using System.Collections;
using UnityEngine;

namespace Assets.Scripts
{
	public class Test : MonoBehaviour
	{
		private class NonUnityObject { }

		private GameObject field;
		private NonUnityObject field2;

		private void Start()
		{
			field = new GameObject();
			field2 = new NonUnityObject();
		}
	}
}
```

#### Expected behavior
Both field and field2 shouldn't have any warnings about not being assigned on initialization, since both of them are assigned on Start.

#### Screenshots
![image](https://user-images.githubusercontent.com/6932278/147386689-b8f2eb64-69f4-4c76-9ba7-182ae6b41c06.png)

#### Additional context
This issue is caused by these 2 checks:
https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/d0f2344fc46f4ffbb8233e06cbdb2bcf53bf7d27/src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs#L93

https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/d0f2344fc46f4ffbb8233e06cbdb2bcf53bf7d27/src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs#L120

In both the field and property checks, the analyzer only suppresses the "not initialized" warning if the fields in question inherit from `UnityEngine.Object`, even though their assignment in Start/Awake has nothing to do with whether they are `UnityEngine.Object`s or not.
(Note - I am not sure whether my logic applies to SerializeField. It might be the case that SerializeField requires this check, while Start/Awake don't)

Is there a specific reason for this check that I'm missing? Or is it really not needed? If it really is needed, I suggest adding a comment near that check, and adding info to the null warning, since when I encountered this issue, I was sure this suppression rule wasn't working, and spent a lot of time trying to figure out why.

**Comment by sailro** [comment]
I agree, there is no need for checking if the type is deriving from `UnityEngine.Object` in this specific `CS8618` case. To answer your question, the logic applies correctly to `SerializeField` as well, given you can "Unity-serialize"  arrays, lists and primitive types that are clearly not deriving from `UnityEngine.Object`.

I'm going to remove type checks for field/property analysis, and add a new test re-using your repro.

Thank you!

**Comment by guyguy2001** [comment]
Thanks!
But as far as I remember, I can't serialize `int?` in the editor, although I might be wrong (I will only get home to try to test that in a couple of days)

**Comment by sailro** [comment]
Yes, Unity not only can't show nullable fields in the inspector, it cannot serialize them.

But in the end all those implementation details are outside the scope of this suppressor. 

The main goal is to suppress `CS8618`
- For Unity types containing Unity messages (like `MonoBehaviour` but all other compatible types as well).
- When Fields or properties of such types cannot be initialized next to their declaration but can be assigned to in Unity's initialization methods such as `OnEnable()`, `Awake()`, and `Start()` or all methods called by these, or the inspector.
