### ISSUE TITLE
IDE0016 should be ignored for types inheriting from UnityEngine.Object

### ISSUE THREAD

**Issue by KuraiAndras** [microsoft/Microsoft.Unity.Analyzers#204]
#### Bug description
IDE0016 is reported for types inheriting from the `UnityEngine.Object` class

- Version of analyzers assembly: 1.12.0

#### To Reproduce
Insert the following code snippet
```csharp
    public class Billboard : MonoBehaviour
    {
        [SerializeField] private Camera _camera = default!;

        private void Update() => transform.rotation = _camera.transform.rotation;

        public void SetCamera(Camera nextCamera)
        {
            // IDE0016 is reported here for the throw
            if (nextCamera == null) throw new ArgumentNullException(nameof(nextCamera));
            _camera = nextCamera;
        }
    }
```

#### Expected behavior
IDE0016 is not reported

#### Screenshots
![image](https://user-images.githubusercontent.com/19240945/155980153-1e9b391c-778c-4dab-aef5-bc6cf48b1a16.png)

#### Additional context
This might be applicable for other analyzers where null checking can be simplified

**Comment by sailro** [comment]
Yes I agree, we should create a new Suppressor for this case. 

^@jbevain, what do you think?

**Comment by jbevain** [comment]
Yep, approved!
