### ISSUE TITLE
Unity Flags only Error Rules

### ISSUE THREAD

**Issue by abmaurya** [microsoft/Microsoft.Unity.Analyzers#219]
#### Bug description
If the action for any rule is set to anything but "Error", Unity reports that as warning(even if action is set to "Info"). Further, Unity only reports violation of Rules with ID UNTXXXX in Unity v2020 but no logs in 2022(except Error). 

Other rules of ID IDEXXXX that either come under "Microsoft.CodeAnalysis.CSharp.Features" or "Microsoft.CodeAnalysis.Features" are not being logged at all.

- Version of analyzers assembly: 1.13.0
- Analyzer rule: ANY

#### To Reproduce
Steps or code to reproduce the behavior:
1. Set Action for any rule to "Info" or "Warning" like:
  <Rule Id="UNT0001" Action="Info" />
or <Rule Id="UNT0001" Action="Warning" />
2. Let Unity reload scripts
3. Make changes to any script with an empty Unity message(UNT0001) like:
     void Start()
     {   
     }
4. Let Unity reload/re-import that script
5. No logs or warnings in the console in Unity v2022, Info/Warning => Warning in Unity v2020. Errors => Errors for both.
6. No logs for IDEXXXX rules

#### Expected behavior
For every violation of rule set for Info and Warning action in the ruleset file, the Unity console should print corresponding logs like it does for Errors.

**Comment by sailro** [comment]
Hello @abmaurya, so if my understanding is right, you are using our analyzers directly in your Unity project (like copying the dll, and tagging it as an analyzer in the Unity Editor). 

Given the Unity pipeline is completely closed, did you report this behavior to them? I fear we can do nothing about it on our side. Unity is creating its own compilation/analyzer context using Roslyn and handling results directly.
