### ISSUE TITLE
Warn on calling `Destroy` on a `Transform`

### ISSUE THREAD

**Issue by spaarmann** [microsoft/Microsoft.Unity.Analyzers#226]
#### Problem statement
Calling `Object.Destroy` or `.DestroyImmediate` with a `Transform` argument is always an error and will produce an error message such as this at runtime:
> Can't destroy Transform component of 'GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.

In my experience due to the 1-to-1 relationship between `GameObject`s and `Transform`s, code using a `Transform` as a general handle for a game object is pretty common. It's easy to accidentally attempt to destroy an object via the transform in such cases.

#### Proposed solution
Any call to `Destroy` or `DestroyImmediate` where the first parameter is statically of type `Transform` should at least be warned about. A suggestion to use `.gameObject` on the transform as parameter instead would also be good.

**Comment by sailro** [comment]
Thank you @spaarmann for raising this case. I just created the PR for review.

**Comment by SilentSin** [comment]
> Any call to Destroy or DestroyImmediate where the first parameter is statically of type Transform should at least be warned about.

Also `RectTransform`.

**Comment by sailro** [comment]
> > Any call to Destroy or DestroyImmediate where the first parameter is statically of type Transform should at least be warned about.
> 
> Also `RectTransform`.

Yes, we check for all types extending `Transform`:
https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/61a6442c5598063f7d09a560586efa85f06e38ae/src/Microsoft.Unity.Analyzers/DestroyTransform.cs#L96

And `RectTransform` inherits `Transform` as expected: https://docs.unity3d.com/ScriptReference/RectTransform.html
