### ISSUE TITLE
Is there anyway to support sourcelink for unity debug?

### ISSUE THREAD

**Issue by yebeans** [microsoft/Microsoft.Unity.Analyzers#234]
#### Problem statement
Recently i'm trying to split the low level game modules out of Unity Assets, and pack to NuGet packages (like log、objectpool、thread、pathfinding etc), maintained by NugetForUnity. 
By doing this, it will be easy for sharing common modules across different projects. But it's difficult to debug the source code for game developers.
As i know [sourcelink](https://github.com/dotnet/sourcelink#using-source-link-in-c-projects) could download sourcecode from git dynamically, but it seems not work for "VisualStudio Tools for Unity" 

#### Proposed solution
Is there anyway to support Sourcelink by "VisualStudio Tools for Unity"?  If it works, we can:
1. common modules packed as nuget package A,B,C.
2. develop other common modules out of Unity Project(install dependences from nuget package manager), and packed as another nuget package D.
3.  Install common modules by NuGetForUnity inside Unity Project.
4.  Debug step by step into the common module source code with sourcelink.

**Comment by sailro** [comment]
Hello, this repository is related to Unity analyzers only. So this ticket is out of scope.

But to answer your question, we expect sourcelink to be available out of the box with all the modernization work planned on the Unity side for their build pipeline.

See https://blog.unity.com/technology/unity-and-net-whats-next
