### ISSUE TITLE
Recommend using new Input System package

### ISSUE THREAD

**Issue by bdovaz** [microsoft/Microsoft.Unity.Analyzers#236]
#### Problem statement

As you know, APIs like Input.* are marked as legacy. In the following page you can see how they are in a module called InputLegacyModule:

https://docs.unity3d.com/ScriptReference/UnityEngine.InputLegacyModule.html

In fact, this module includes more APIs than Input, the ideal would be to check all of them but what is going to cover 99% of the cases is to include the Input APIs.

#### Proposed solution

Suggest using the new com.unity.inputsystem package:

https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/QuickStartGuide.html

**Comment by sailro** [comment]
I fully agree, but let's wait a bit given Unity is planning to support the legacy API through the Input System. It is on their roadmap to address this dilemma between the old and the new system.

And a lot of users are still using the legacy one for now (Unity advice is to keep up and running if it works and does the job).

We'll re-open this ticket given their progress.

Thanks!

**Comment by bdovaz** [comment]
I don't understand when you say "Unity is planning to support the legacy API through the Input System", it already does, there is a guide to see what is the equivalent of each API:

https://docs.unity3d.com/Packages/com.unity.inputsystem@1.4/manual/Migration.html

In our case we would like to have this analyzer to be able to know which old APIs we are using in our own code incorrectly, without an analyzer it is easy to leave one unintentionally.

And for using third party assets we have to have the input configured in "both", we can't just put the new one which would be ideal.
