### ISSUE TITLE
UNT0006 doesn't support the new AssetPostprocessor.OnPostprocessAllAssets signature

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#237]
#### Bug description

In Unity 2021, [OnPostProcessAllAssets](https://docs.unity3d.com/ScriptReference/AssetPostprocessor.OnPostprocessAllAssets.html) has an optional `didDomainReload` parameter which causes UNT0006 to claim it has an incorrect signature.

#### To Reproduce

1. Make an `AssetPostprocessor` class.
2. Give it an `OnPostprocessAllAssets` method with the optional `didDomainReload` parameter.

**Comment by sailro** [comment]
Indeed, I do not think we have a support for optional parameters

**Comment by sailro** [comment]
Ah ok so technically speaking it is not an optional parameter, but a new message overload. I added it to our message stubs and now all is working properly.
