### ISSUE TITLE
Warn against asset loading in [InitializeOnLoad] and [InitializeOnLoadMethod]

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#238]
#### Problem statement
In older versions of Unity with Asset Database V1, you could use `AssetDatabase.LoadAsset` in an `[InitializeOnLoad]` method.

In newer versions of Unity with Asset Database V2, you can't. It always returns `null` and gives no indication as to why.

`AssetDatabase.FindAssets` also fails but `AssetDatabase.GUIDToAssetPath` doesn't.

[The forum thread has more details and an explanation from a Unity dev as to why it was changed.](https://forum.unity.com/threads/initializeonloadmethod-sometimes-can-run-before-the-assetdatabase-is-actually-ready-to-load-things.1325043/#post-8380110)

#### Proposed solution
The [documentation for [InitializeOnLoad]](https://docs.unity3d.com/ScriptReference/InitializeOnLoadAttribute.html) explains the solution:

> Asset operations such as asset loading should be avoided in InitializeOnLoad methods. InitializeOnLoad methods are called before asset importing is completed and therefore the asset loading can fail resulting in a null object. To do initialization after a domain reload which requires asset operations use the [AssetPostprocessor.OnPostProcessAllAssets](https://docs.unity3d.com/ScriptReference/AssetPostprocessor.OnPostProcessAllAssets.html) callback. This callback supports all asset operations and has a parameter signaling if there was a domain reload.

Having a code fix to generate an `AssetPostprocessor` class would be neat, but probably take way more effort than it's actually worth. I'd be satisfied just getting a warning that my asset loading won't work.

Note that the same applies to `[InitializeOnLoadMethod]` even though its documentation doesn't mention it.

**Comment by sailro** [comment]
Perhaps for consistency we should warn as soon as `AssetDatabase` is used in a method decorated with `InitializeOnLoad` or in a static ctor of a class decorated with `InitializeOnLoad`.

**Comment by sailro** [comment]
And we can extend to all LoadAttribute types: `UnityEditor.InitializeOnLoadMethodAttribute`, `UnityEditor.Callbacks.DidReloadScripts`, `UnityEngine.RuntimeInitializeOnLoadMethodAttribute`

**Comment by SilentSin** [comment]
Probably not `[RuntimeInitializeOnLoadMethod]` because it's only called when entering Play Mode, not as a result of potentially incomplete asset importing.
