### ISSUE TITLE
SetLocalPositionAndRotation

### ISSUE THREAD

**Issue by smitdylan2001** [microsoft/Microsoft.Unity.Analyzers#244]
#### Problem statement
Unity introduced transform.SetLocalPositionAndRotation in unity 2021.3.11f1 and 2023.1.0a11 (with all of the latest releases probably getting it).
This is the same performance benefit as transform.SetPositionAndRotation, which already is an analyzer.

#### Proposed solution
Having an analyzer with a check if the unity version is new enough and if so give the message to change sequential .localPosition and .localRotation into .SetLocalPositionAndRotation

**Comment by sailro** [comment]
Indeed, it makes sense.

**Comment by sailro** [comment]
All good. It's now included.
