### ISSUE TITLE
UNT0026 fix removed necessary code

### ISSUE THREAD

**Issue by JVimes** [microsoft/Microsoft.Unity.Analyzers#248]
#### Bug description

UNT0026 has the potential fix "Use TryGetComponent instead", which removed `hit != null` resulting in a NullReferenceException:

```c#
if (hit != null)
    platform = hit.GetComponent<MovingPlatform>();
if (platform != null)
    transform.parent = platform.transform;
```

Which became:

```c#
if (hit.TryGetComponent<MovingPlatform>(out platform))
    transform.parent = platform.transform;
```

- Version of analyzers assembly: _Sorry, how do I check?_
- Analyzer rule: UNT0026

#### Expected behavior

```c#
if (hit != null && hit.TryGetComponent<MovingPlatform>(out platform))
    transform.parent = platform.transform;
```

**Comment by sailro** [comment]
Thank you for this feedback. This is now fixed.
