### ISSUE TITLE
UNT0005 is not actually helpful

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#26]
[UNT0005 Time.deltaTime used with FixedUpdate](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/UNT0005.md)

Accessing `Time.deltaTime` in `FixedUpdate` gives the exact same value as `Time.fixedDeltaTime` so using `fixedDeltaTime` has no actual benefit, but it causes problems if you later move that code into another method that isn't called by `FixedUpdate`.

**Comment by sailro** [comment]
This one was made for consistency with [UNT0004](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/UNT0004.md), but re-reading the [Unity docs](https://docs.unity3d.com/ScriptReference/Time-fixedDeltaTime.html):

> For reading the delta time it is recommended to use Time.deltaTime instead because it automatically returns the right delta time if you are inside a FixedUpdate function or Update function.

**Comment by AnBucyk** [comment]
Seems like we can roll that behavior into UNT0004 and get rid of UNT0005 then?

**Comment by jbevain** [comment]
Agreed, let's make sure we follow Unity's documentation and remove the analyzer for 0005.

**Comment by sailro** [comment]
Note we have to update `ConsistencyTests`, because we check for contiguousity and unicity.

**Comment by jbevain** [comment]
@sailro what about keeping the suppressor but making it a no-op, and properly document it has been retired?

**Comment by sailro** [comment]
I was thinking of that as well. We can possibly make it silent by default, and users can even re-enable it with a ruleset/editorconfig instruction if the behavior matches their needs.
