### ISSUE TITLE
Request for Separate Microsoft.Unity.Analyzers.dll File for VSCode Unity Package Integration

### ISSUE THREAD

**Issue by Chizaruu** [microsoft/Microsoft.Unity.Analyzers#278]
The Microsoft.Unity.Analyzers.dll is included in the NuGet package for Unity development. However, to use it independently in a Visual Studio Code (VSCode) Unity package, it would be beneficial to also have Microsoft.Unity.Analyzers.dll available as a separate file.

Furthermore, integrating the dll from the NuGet package into my VSCode package could be more convenient and efficient. For example, I have to manually extract the dll from the NuGet package and use a workaround to implement its usage in my VSCode package. This process could be streamlined with an automated way to download the dll and place it where needed, particularly for implementing version checks for automatic analyzer updates.

Let's discuss and work towards making this improvement for the Unity community, aiming for easier integration and enhanced functionality of Microsoft.Unity.Analyzers.dll in VSCode Unity packages. 

Please find more information about my VSCode package [here](https://github.com/Chizaruu/com.tsk.ide.vscode).

**Comment by Chizaruu** [comment]
Possibly not required anymore.

I started working on using the nuget package directly, and after some tests, it looks quite promising.

**Comment by Chizaruu** [comment]
Closing due to solution working. Please continue the excellent work.

**Comment by sailro** [comment]
Hello,

There is now built-in support for generating projects for vscode using analyzers :
https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/

Regards
