### ISSUE TITLE
Warn about unnecessary indirection through transform and gameObject

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#28]
#### Problem statement

A simple problem I've seen from beginners is where they use `.transform` or `.gameObject` when it isn't necessary, wasting a bit of performance and making the script longer:

```
private void Awake()
{
    // Bad:
   transform.name = "Something";
    // Good:
   name = "Something";

    // Bad:
   gameObject.transform.position = Vector3.zero;
    // Good:
   transform.position = Vector3.zero;
}

private void OnTriggerEnter(Collider collider)
{
    // Bad:
    collider.gameObject.GetComponent<Rigidbody>();
    // Good:
    collider.GetComponent<Rigidbody>();
}
```

#### Proposed solution

Remove the unnecessary indirection.

**Comment by jbevain** [comment]
Thank you for filing this.

That obviously makes sense, let see how we could implement that. Basically, if the script is doing:

`this.gameObject.X` and `X` is also defined on the type for `this` which should extend `MonoBehaviour`, we should able to offer to remove the indirection.

We would also apply this for `this.transform.X`.

@SilentSin makes sense?

**Comment by SilentSin** [comment]
Yeah, pretty much that but not specifically limited to `this`.

It should cover `x.gameObject.y` and `x.transform.y` where:

- `x` is any `GameObject` or `Component`.
- And `y` exists in any of the base types of `x` (`GameObject`, `MonoBehaviour`, `Behaviour`, or `Component`, but not in user defined types because they could obviously have a different implementation).

Now that I think about it, it can probably cover `x.GetComponent.y` as well.

**Comment by sailro** [comment]
https://github.com/microsoft/Microsoft.Unity.Analyzers/pull/132
