### ISSUE TITLE
VS Code No quick fixes available

### ISSUE THREAD

**Issue by Werasilz** [microsoft/Microsoft.Unity.Analyzers#287]
![Screenshot 2023-07-13 223714](https://github.com/microsoft/Microsoft.Unity.Analyzers/assets/24826201/09b33fa4-108b-405a-97b5-4aa3f76ed833)

VS Code 1.80.0
C# Extension 1.26.0

I try to use ctrl+. it shows "no code actions available"

**Comment by Werasilz** [comment]
it seems like because of Unity 2022 LTS.
in Omnisharp Log
`[fail]: OmniSharp.MSBuild.ProjectManager
        Failure while loading the analyzer reference 'Unity.SourceGenerators': Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.`
but in Unity 2021 LTS it's working, MSBuild does not fail

**Comment by sailro** [comment]
The issue regarding netstandard 2.1 is clearly a Unity issue (they are working on a fix), but I do not think this one is related to your main issue.

We recently worked with Roslyn/LSP team to address analyzer issue, and I think all will be addressed in an upcoming C# extension release. but probably the v2,x series).
