### ISSUE TITLE
Validate signature for [RuntimeInitializeOnLoadMethod]

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#29]
#### Problem statement

```
// Works:
[RuntimeInitializeOnLoadMethod]
private static void Initialise() { }

// Doesn't work (not static):
[RuntimeInitializeOnLoadMethod]
private void Initialise() { }

// Doesn't work (not parameterless):
[RuntimeInitializeOnLoadMethod]
private static void Initialise(int i) { }
```

#### Proposed solution

Give a warning if the attributed method is not static because Unity won't call it.

Give an error if the attributed method has any parameters because Unity will throw a NullReferenceException when trying to call it (tested in 2019.3.2f1).

Return values are fine.

The same probably applies to `UnityEditor.InitializeOnLoadMethod`.

**Comment by sailro** [comment]
We made the `UNT0009` rule for `InitializeOnLoad`, checking for a static ctor.

But we have nothing so far for `RuntimeInitializeOnLoadMethod` nor `InitializeOnLoadMethod`
