### ISSUE TITLE
Suppress IDE0041 for UnityEngine.Objects

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#291]
# Problem statement

I want to check if my reference is actually null, not destroyed.

- Trying to use `if (obj is null)` gives [UNT0029](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0029.md).
- Trying to use `if (ReferenceEquals(obj, null))` gives [IDE0041](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0041).

That leaves no option for achieving the desired behaviour without suppressing a warning.

# Proposed solution

Suppress [IDE0041](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0041) because no sane person is going to write `ReferenceEquals(obj, null)` if that isn't exactly what they want.

# Alternative solution

Remove [UNT0029](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0029.md) because there's no reason to use `is` instead of `==` unless you actually want a reference equality check.

**Comment by jbevain** [comment]
Agreed about the proposed solution.
