### ISSUE TITLE
FixAll of UNT0021 doesn't work

### ISSUE THREAD

**Issue by nyroro** [microsoft/Microsoft.Unity.Analyzers#308]
#### Bug description
FixAll of UNT0021 doesn't work

- Version of analyzers assembly: 1.18.0
- Analyzer rule: UNT0021
- Error (exception message, type, and callstack where applicable): No

#### To Reproduce
Steps or code to reproduce the behavior:
1. Go to code with private void Awake() and private void OnEnable()
2. Click on FixAll and select Document
![QQ截图20240107193904](https://github.com/microsoft/Microsoft.Unity.Analyzers/assets/1767874/541e3ae8-1b7c-4035-9c42-b12d9d425f9f)

![图片](https://github.com/microsoft/Microsoft.Unity.Analyzers/assets/1767874/2be93259-6153-4454-89ce-e5d841ef81b5)

3. Only fix the one that click with. The other one is not fixed
![QQ截图20240107193919](https://github.com/microsoft/Microsoft.Unity.Analyzers/assets/1767874/d449f807-ef66-42c5-9782-38c00152629f)

#### Expected behavior
Expecte to fix the 2 UNT0021 in the same document.

**Comment by sailro** [comment]
Hello and thank you for this report. I'm currently investigating.

I also found a related bug with this analyzer when using messages with comments and without scope modifiers, so fixing this as well.

**Comment by sailro** [comment]
I found and fixed the root issue. Thanks!
