### ISSUE TITLE
IDE0270 should be suppressed by the UnityObjectNullHandlingAnalyzer

### ISSUE THREAD

**Issue by JorisCleVR** [microsoft/Microsoft.Unity.Analyzers#323]
#### Problem statement
UnityObjectNullHandlingAnalyzer now supresses IDE0029 but not IDE0270. This causes IDE0270 to suggest null coalesce on Unity objects.
The following code example raises IDE0270
```
using UnityEngine;

class Camera : MonoBehaviour
{
	public void M()
	{
		Camera item = FindItem() as Camera;
		if (item == null)
			throw new System.InvalidOperationException();
	}

	MonoBehaviour FindItem() => null;
}
```

#### Proposed solution
Add IDE0270 as a supressor to the UnityObjectNullHandlingAnalyzer

**Comment by JorisCleVR** [comment]
I know that the issue is not yet approved, but I am confident about this fixing issues. Therefore I already created a pull request to hopefully be merged once this issue is approved: https://github.com/microsoft/Microsoft.Unity.Analyzers/pull/324

**Comment by sailro** [comment]
Indeed, thank you for this contribution !
