### ISSUE TITLE
Visual Studio discontinuation for MacOS

### ISSUE THREAD

**Issue by marcospgp** [microsoft/Microsoft.Unity.Analyzers#325]
> We are focusing our efforts on the experience brought by our IDEs (Visual Studio and Visual Studio for Mac)

<https://visualstudio.microsoft.com/vs/mac/>

> Retiring on August 31, 2024

Are there plans for officially supporting VSCode?

**Comment by sailro** [comment]
Hello @marcospgp,

Yes VSCode is now fully supported. More information here:

https://marketplace.visualstudio.com/items?itemName=VisualStudioToolsForUnity.vstuc

Our analyzers are shipped with the Unity extensions. Make sure you are using a recent VS Editor Package in your Unity project..

**Comment by marcospgp** [comment]
> Our analyzers are shipped with the Unity extension

I actually just noticed this, but couldn't find the information anywhere. Just randomly decided to look in the generated `.csproj` file 😅
