### ISSUE TITLE
Suppression of IDE0029, IDE0031, IDE0051 does not work anymore in Visual Studio 17.12.1

### ISSUE THREAD

**Issue by JorisCleVR** [microsoft/Microsoft.Unity.Analyzers#364]
#### Bug description
In the Error List of visual studio the following warning are available on Unity objects:
IDE0029, IDE0031, IDE0051

- Version of analyzers assembly: Visual Studio 17.12.1 (Including Game development with Unity)
- Analyzer rule: IDE0029, IDE0031, IDE0051

#### To Reproduce
Steps or code to reproduce the behavior:
1. Install Visual Studio 17.12.1 (Including Game development with Unity)
2. Create IDE0029, IDE0031 on a Unity object
3. Create IDE0051 by adding Start method to a MonoBehaviour

#### Expected behavior
These warnings are suppressed for Unity objects and inside of the MonoBehaviour

**Comment by sailro** [comment]
Hello @JorisCleVR 

This issue is tracked here:
https://developercommunity.visualstudio.com/t/Private-Unity-messages-incorrectly-marke/10779025

The root issue is in Roslyn,  a component our analyzers depends on.

Regards
