### ISSUE TITLE
Recommend Unity messages be protected

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#42]
#### Problem statement
Unity messages like `Awake`, `Update`, etc. do not need to be `public` for Unity to call them and are only rarely meant to be called manually.

Also, if a base class has a `private` message and a child class implements the same one, only the child one will be called without any notification or any way to call the base method, which is pretty much guaranteed to cause bugs.

#### Proposed solution
Recommend that all Unity messages be `protected`. Give a warning if they are `private`, but only a suggestion otherwise.

Inside `sealed` classes, either disable that suggestion or suppress `CS0628 // New protected member declared in sealed class`.

**Comment by jbevain** [comment]
The reasoning is sound. I'm a bit afraid that this would pop-up a suggestion as soon as you create a new script in Unity, as the templates there create private fields.

**Comment by SilentSin** [comment]
I don't think that should be a problem because those methods already trigger [UNT0001](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/UNT0001.md) don't they?

I'm tempted to propose another analyser that detects that pattern (empty Start and Update methods) and tells you to go and edit your default script template (which is probably not possible for an analyser?) because it's kind of stupid. Those default methods are by far the most common reason for violations of UNT0001 I've seen and also a very common source of comments being incorrect when people rename the method without removing the comments.

**Comment by jbevain** [comment]
The expectations are a bit different however, as we're expecting the user to write code in `Start` and `Update` shortly after creating a new script.

But then again, I agree that's something we should do.

As far as suggesting the user to modify the default template, that's a bit outside of our scope :)

**Comment by SilentSin** [comment]
We're expecting them to write *something*, but not necessarily in `Start` or `Update`.

A quick search in the project I currently have open (355 files) found:

- 1 `Start` method (in a 3rd party plugin).
- 55 `Awake` methods.
- 37 `Update` methods.

Obviously the statistics will be wildly different for everyone according to their preferences, but for me that's like a 90% chance of triggering UNT0001 on both methods in every new script if I still used the default template (and counting `Awake` as `Start` only drops it closer to 80%).

**Comment by sailro** [comment]
We added this analyzer and codefix, but as an opt-in choice.

To enable-it you'll need the following in your `.editorconfig` file.

```editorconfig
[*.cs]
dotnet_diagnostic.UNT0021.severity = suggestion
```
