### ISSUE TITLE
Will this project be published on NuGet?

### ISSUE THREAD

**Issue by alexrp** [microsoft/Microsoft.Unity.Analyzers#57]
A NuGet package would be helpful for running analyzers as part of CI and command line builds, and would make the analyzers available to VS Code users as well. I don't know exactly what work this would entail, but I imagine it should be possible to ship the analyzers on NuGet in a similar manner to [the Roslyn Analyzers](https://github.com/dotnet/roslyn-analyzers).

**Comment by jbevain** [comment]
Right now we're focusing our effort on the experience brought by our IDEs (Visual Studio and Visual Studio for Mac) with Unity where those analyzers ship in the box.

I'm not opposed to shipping them on NuGet as for people building class librairies for Unity outside of Unity, but right now that would be a fringe scenario. I'm happy to revisit if we get multiple requests.

**Comment by jeffcampbellmakesgames** [comment]
I have a a related question; but would it be possible to create releases containing extension installers for these analyzers?

**Comment by jbevain** [comment]
Hi @jeffcampbellmakesgames,

We don't plan to release self contained Visual Studio extensions for those analyzers. The main reason is that not all suppressors will work if they're not being referenced as part of the project, and loaded in the IDE instead.

**Comment by jeffcampbellmakesgames** [comment]
> Hi @jeffcampbellmakesgames,
> 
> We don't plan to release self contained Visual Studio extensions for those analyzers. The main reason is that not all suppressors will work if they're not being referenced as part of the project, and loaded in the IDE instead.

Gotcha, makes sense. Thanks for the info!

**Comment by jbevain** [comment]
Closing this for now as per the comments above.

**Comment by alexrp** [comment]
I decided to try my hand at packaging this project for NuGet in https://github.com/alexrp/Microsoft.Unity.Analyzers/commit/ce6d270a2722d06fcf4506483dc6ed5f76c9e2ac. It seems to be working fine, so I've published an unofficial package [here](https://www.nuget.org/packages/Unofficial.Microsoft.Unity.Analyzers/). Usage:

```xml
<PackageReference Include="Unofficial.Microsoft.Unity.Analyzers" Version="1.0.0" PrivateAssets="all" />
```

Anyone who's in a similar boat to me can give it a try. I suppose it's also a good way to gauge interest in an official package.

(If you decide to build official packages for this project at some point, I'll deprecate + unlist this one in favor of that.)

**Comment by sailro** [comment]
Hello folks,

An update regarding this topic: we started producing an official/Microsoft-signed NuGet package here:

https://www.nuget.org/packages/Microsoft.Unity.Analyzers/

@alexrp could you please unlist your Unofficial version please ?

Let us know if you face any issues.

Thanks!

**Comment by alexrp** [comment]
That's great news! I've deprecated + unlisted the unofficial package.

**Comment by alexrp** [comment]
@sailro By the way, I think you're missing `<DevelopmentDependency>true</DevelopmentDependency>` in the official package.

**Comment by sailro** [comment]
Ah good catch

**Comment by sailro** [comment]
Using a <PrivateAssets>all</PrivateAssets> under your PackageReference directive should workaround this until we publish a new version. Thanks!

**Comment by aubergine10** [comment]
Ah, great to see it as separate package! And thanks @alexrp who's unofficial package we were previously using.
