### ISSUE TITLE
Fields of ScriptedImporter should be treated like MonoBehaviours.

### ISSUE THREAD

**Issue by jbevain** [microsoft/Microsoft.Unity.Analyzers#59]
#### Bug description
Types extending `ScriptedImporter` expose public or [SerializeField] fields like fields in a MonoBehaviour.

See:

https://github.com/Unity-Technologies/AlembicForUnity/blob/master/com.unity.formats.alembic/Editor/Importer/AlembicImporter.cs

For instance.

#### Expected behavior
This means we should treat those fields like fields of a MonoBehaviour, suppress the `CS0649` warning and prevent refactoring suggestions like making them `readonly`.

**Comment by sailro** [comment]
I just had a look.

It's already working for:
- `SerializeFieldSuppressor` (`IDE0044`, `IDE0051` and `CS0649`)
- `ImproperSerializeFieldAnalyzer`

We do not check the `ContainingType`.

![image](https://user-images.githubusercontent.com/638167/82081617-7b3e5000-969b-11ea-8756-502b48ff50c9.png)

![image](https://user-images.githubusercontent.com/638167/82081674-9610c480-969b-11ea-8d51-12c82af5e2c4.png)

So I think we can close this one.
