### ISSUE TITLE
Visual Studio relies on an old snapshot and shows non-existent issues

### ISSUE THREAD

**Issue by aybe** [microsoft/Microsoft.Unity.Analyzers#69]
#### Bug description

Even though project is rebuilt, cleaned, etc, the green squiggles in Solution Explorer do not disappear, **except** when you disable _Disable the full build of projects_. As soon as you do that the problem is instantly fixed.

Visual Studio Version 16.5.4
VSTU 4.6.0.0 Experimental
also installed Microsoft Code Analysis 2019 3.0.0.1925803

#### To Reproduce
Steps or code to reproduce the behavior:
1. edit your code until you trigger some of these analyzers
2. do some work that rebuilds the project
3. see that errors are non-existent
4. now disable _Disable the full build of projects_.
5. rebuild your project
6. analyzer errors are now gone

#### Expected behavior

_Disable the full build of projects_ should not influence the analysis.

(in Tools/Options/Tools for Unity)

#### Screenshots

Also, here all the extensions I have installed:

![devenv_2020-04-28_05-20-38](https://user-images.githubusercontent.com/1537591/80443661-04b9f800-8910-11ea-8828-2545000eb5d4.png)

![devenv_2020-04-28_05-21-07](https://user-images.githubusercontent.com/1537591/80443688-13081400-8910-11ea-96b6-b9ee766ff837.png)

**Comment by sailro** [comment]
Thanks for the feedback!

This is not an issue related to this Analyzers project but rather a VSTU/VSTUM issue with our lightweight build feature.

So I'm going to close this ticket, and we'll continue discussing this offline.

Regards
Seb
