### ISSUE TITLE
C# 8 null coalescing assignment

### ISSUE THREAD

**Issue by jbevain** [microsoft/Microsoft.Unity.Analyzers#70]
#### Problem statement
C# 8 introduces the `??=` operator, which is not going to work with `UnityObject`.

#### Proposed solution
Just like `??`, we should make sure Visual Studio doesn't offer to use that operator.

**Comment by therealjohn** [comment]
I looked into this a little and it seems to require updating some bits of the test framework so that C# 8 analyzers/suppressors are discovered.

**Comment by sailro** [comment]
I upgraded the infrastructure to be able to properly detect this (for a suppressor).

The following test will trigger a `Test0.cs(11,18): info IDE0074: Use compound assignment`

```csharp
using UnityEngine;

class Camera : MonoBehaviour
{
    public Transform a = null;
    public Transform b = null;

    public Transform NC()
    {
        return a ?? (a = b);
    }
}
```

documentation:
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0054-ide0074
