### ISSUE TITLE
Set Position and Rotation

### ISSUE THREAD

**Issue by ArturoNereu** [microsoft/Microsoft.Unity.Analyzers#74]
#### Problem statement
Accessing the transform should be done as few times as possible for performance reasons. If this is still needed in cases such as: 

transform.position = newPosition;
transform.rotation = newRotation;

#### Proposed solution
Whenever users set the position they should do it using:

transform.SetPositionAndRotation(newPosition, newRotation);

**Comment by jbevain** [comment]
Thanks @ArturoNereu! Good to see you here, keep them going, this is a great one.

**Comment by sailro** [comment]
This API is available since Unity 5.6, so we probably don't need to check the version here.
