### ISSUE TITLE
Use TryGetComponent to prevent memory allocation

### ISSUE THREAD

**Issue by therealjohn** [microsoft/Microsoft.Unity.Analyzers#76]
Recommended on Twitter as part of #unitytips 

https://twitter.com/BinaryImpactG/status/1265191692531044352?s=20

#### Problem statement
Users want to check if a component exists on a GameObject.

#### Proposed solution
When using GetComponent and null checking the result, TryGetComponent can be used instead and prevents memory allocation. 

Note, API is available in 2019.2+

**Comment by jbevain** [comment]
This one is interesting because it requires knowing the version of Unity, or at least validating in the referenced Unity assembly that this method actually exists.

**Comment by sailro** [comment]
`TryGetComponent` is defined in `Component` and `GameObject`, starting with `Unity 2019.2`

Perhaps we can use Roslyn's `Project.ParseOptions.PreProcessorSymbolNames` and search for `UNITY_2019_2_OR_NEWER` ?
But this will only work for projects generated from Unity (not handcrafted c# libs).

We also need to upgrade the test infrastructure to use preprocessor symbols like this:
```csharp
project = project
    .WithParseOptions(((CSharpParseOptions)project.ParseOptions)
    .WithPreprocessorSymbols("UNITY_2019_2_OR_NEWER"));
```

**Comment by jbevain** [comment]
@sailro I think the safest is just to look at the symbols of the referenced assembly from the current context.

**Comment by imniko** [comment]
Any update on this?
