### ISSUE TITLE
how to install analyzers

### ISSUE THREAD

**Issue by ghosttie** [microsoft/Microsoft.Unity.Analyzers#80]
I don't understand how I'm supposed to install the analyzers - I've got the latest version of VS installed, and if I open a script from Unity it opens in VS but I don't see anything from the Unity analyzers

Is there something else I'm supposed to install?  Am I supposed to build this repo myself in order to use it?  It's not very clear...

**Comment by sailro** [comment]
Hello, we ship all analyzers along with VS and VS for mac. When the project is generated from Unity, we'll automatically add a reference to our analyzer assembly:

![image](https://user-images.githubusercontent.com/638167/83535741-2ece7f00-a4a7-11ea-83ad-67bb6065c6bc.png)

And you should see diagnostics in your error list:
![image](https://user-images.githubusercontent.com/638167/83535895-66d5c200-a4a7-11ea-94ba-34636ccba13b.png)

**Comment by ghosttie** [comment]
I've got nothing under Analyzers in the Solution Hierarchy, and if I right click and choose Add Analyzer it says "No items found for search term(s)"

**Comment by sailro** [comment]
What are your exact VS and Unity versions?

**Comment by ghosttie** [comment]
Microsoft Visual Studio Community 2019 Version 16.6.1
Unity 2017.4.24f1 LTS

Maybe my version of Unity is too old?

**Comment by sailro** [comment]
Indeed, we only added analyzers to the new project generation system so far (so 2018.2+ I think)

 but you can do something like this with the legacy system:
- create an Editor script to automatically alter the csproj: https://gist.github.com/sailro/603a57f81322950b926bbbd136ce81bd
- use this script to inject the following:
```xml
  <ItemGroup>
    <Analyzer Include="C:\Program Files (x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll" />
  </ItemGroup>
```

**Comment by ghosttie** [comment]
Thanks

It might be a good idea adding this to the documentation somewhere - Unity is notorious for breaking changes so I think a lot of people stay on old versions

**Comment by sailro** [comment]
This should only be transitory, because we have backported the change to include the analyzers in the legacy generation, but it's not published yet.
