### ISSUE TITLE
Suppress CA1822 for MonoBehaviour messages

### ISSUE THREAD

**Issue by aubergine10** [microsoft/Microsoft.Unity.Analyzers#81]
#### Problem statement

Consider this `LateUpdate()` on a `MonoBehaviour`:

```cs
        [UsedImplicitly]
        protected void LateUpdate()
        {
            DoSomethingNotInstanceRelated();
        }
```
[CA1822](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822?view=vs-2019) suggets to mark the member as static for performance reasons.

However, Unity messages will not be processed if they are marked `static`; it would be a breaking change.

#### Proposed solution

CA1822 should be suppressed for [MonoBehaviour messages](https://docs.unity3d.com/ScriptReference/MonoBehaviour.html).

**Comment by sailro** [comment]
For the context `CA1822` is coming from the `Microsoft.CodeAnalysis.FxCopAnalyzers` package.

While playing with this analyzer package, I spotted other rules that we already suppressed for CS/IDE warnings like:

- `CA1051`: Do not declare visible instance fields (on serialized fields)
- `CA1801`: Parameter layerIndex of method OnAnimatorIK is never used. Remove the parameter or use it in the method body.
- `CA1823`: Unused field 'X' (on serialized fields).
- `CA1812`: X is an internal class that is apparently never instantiated.
