### ISSUE TITLE
Don't use anything from `System.Reflection` namespace in `Update()` loop

### ISSUE THREAD

**Issue by aubergine10** [microsoft/Microsoft.Unity.Analyzers#83]
#### Problem statement

This is disturbingly common in commuinity submitted mods, especially small "that couldn't possibly be the cause of the lag" mods:

```cs
public class DecimateFps : MonoBehaviour
{
   protected void Update()
   {
        // Code using `System.Reflection` to get/set private properies
   }
}
```

Is also disastrous in `LateUpdate()`, `OnGUI()`, etc.

Often the `System.Reflection` code will be contained in a separate method - I'm not sure if the analyzer can track that down? Such methods often have a signature similar to `Q ReadPrivate<T, Q>(T o, string fieldName)` or `WritePrivate<T, Q>(T o, string fieldName, object value)`.

#### Proposed solution

No code fix suggestion for this, it just needs flagging to user as a warning.

> Performance: Never use `System.Reflection` features in performance critical messages.

Docs could mention:

> If you must use `System.Reflection` to access a private member, consider caching `FieldInfo` or `MethodInfo` in `Start()`, or elsewhere, and use the cached references in the loop instead.
>  
> In many cases alternatives are available which don't require reflection. For example, if a game object has a private field referencing a UI component, a direct reference to the component can be obtained using code such as `FindObjectOfType<SomeGO>().GetComponent<T>()`; the component can be cached and subsequently directly accessed in the update loop.

**Comment by sailro** [comment]
Yes we are thinking as well on doing this kind of analysis.
