### ISSUE TITLE
Give an error when using GameObject.gameObject

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#92]
# Problem statement
In relation to https://github.com/microsoft/Microsoft.Unity.Analyzers/issues/28, I just found out that `GameObject`s actually have a `gameObject` property which is undocumented but seems to just `return this`, so you can do `gameObject.gameObject.gameObject.gameObject...`.

And the same for `transform`.

# Proposed solution
Unless I'm missing something, it seems to do absolutely nothing so it should give an error any time you use it.

**Comment by sailro** [comment]
Indeed:

![image](https://user-images.githubusercontent.com/638167/87172103-8de29900-c288-11ea-8423-3bf738f0c499.png)
