### ISSUE TITLE
CA2235 on String in Serializable

### ISSUE THREAD

**Issue by aybe** [microsoft/Microsoft.Unity.Analyzers#97]
#### Problem statement

Unity supports this scenario actually, strings do get serialized.

![devenv_2020-06-26_21-31-02](https://user-images.githubusercontent.com/1537591/85894229-a1a3ef00-b7f4-11ea-8287-0ce22377402f.png)

#### Proposed solution

If the type lies in an asmdef or Assembly-CSharp, Assembly-Editor-CSharp then I guess the analyzer should be aware of that fact.

**Comment by sailro** [comment]
See https://github.com/dotnet/roslyn-analyzers/issues/3616 and https://github.com/dotnet/roslyn-analyzers/issues/1712

In this case, it seems to be part of false positives with `Microsoft.CodeAnalysis.FxCopAnalyzers`. Could you try to upgrade ? 

Should be fixed with 2.9.X, and v3.0.0 is available since 2 months.

**Comment by aybe** [comment]
I thought FxCop was a different package, but after following instructions I realized I already have Code Analysis 3.0.0.1925803:

https://docs.microsoft.com/en-us/visualstudio/code-quality/install-roslyn-analyzers?view=vs-2019

But when I look at Analyzers in Solution Explorer, I don't have all these like in docs, only Microsoft.Unity.Analyzers, and obviously, no CA2235 in it.

I've also tried enabling the new Enable Roslyn analyzers in Unity but without much effect.

**Comment by sailro** [comment]
Given you installed a `vsix`, those FxCop analyzers are enabled for every project. In the solution explorer you can only see local packages specific to the current project (this is what we do for this project).

**Comment by sailro** [comment]
Closing this one, as this is not related to the Unity scenario, but more an issue with the CA2235 diagnostic / FxCop project. Feel free to comment in the case I'm wrong.
