### ISSUE TITLE
Suppress unused methods for EditWindow, ScriptableObject, etc subclasses

### ISSUE THREAD

**Issue by therealjohn** [microsoft/Microsoft.Unity.Analyzers#98]
#### Problem statement
The same principal as https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs but for other Unity subclasses with special method messages like EditorWindow

#### Proposed solution
Similar solution as https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs

**Comment by sailro** [comment]
Is it really for [`USP0008`](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/USP0008.md) ? Because `Invoke`, `InvokeRepeating`, `StartCoroutine` or `StopCoroutine` are only defined for a MonoBehaviour if I'm not wrong ?

**Comment by therealjohn** [comment]
Edited my proposal. I misunderstood `USP0008`.

**Comment by therealjohn** [comment]
This should already work: https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/src/Microsoft.Unity.Analyzers/ScriptInfo.cs#L16

I believe I incorrectly opened the solution from VS instead of from Unity and it loaded as a normal C# project.
