### ISSUE TITLE
C# 8 nullable reference types

### ISSUE THREAD

**Issue by Mindstyler** [microsoft/Microsoft.Unity.Analyzers#99]
#### Problem statement
C# 8 introduced nullable reference types. Since fields/properties of unity types cannot be initialized in conjunction with the variable declaration, CS8618 warnings should be suppressed for all those fields/properties.

#### Proposed solution
Suppress CS8618 warnings for fields/properties of types that inherit from not initializable unity types and are not assigned to in Unity's initialization methods ('OnEnable()', 'Awake()', 'Start()') or the inspector. Should there be no assignment CS8618 should still be thrown.

**Comment by Mindstyler** [comment]
I've written this analyzer in the last few days and would submit a Pull request once this problem gets approved.

**Comment by sailro** [comment]
Hi @Mindstyler, sure. Thanks!

**Comment by Mindstyler** [comment]
Hey, I'm pretty new to Github and I cannot publish a new branch to this project for my Pull request because of insufficient write access. Is there something I'm missing?
